services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    user: root
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Passw0rd!'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_TCP_PORT: 1433
      MSSQL_PID: 'Developer'
    volumes:
      - unq-msql-data:/var/opt/mssql/data
    ports:
      - "1433:1433"

volumes:
  unq-msql-data:


